PROGRAM := pixie_renderer_demo
SOURCES := main.c ../../shared/pixie_renderer/pixie_renderer.c
EXTRA_DEPS := ../../shared/generated/time-pilot-parachutists.h \
	../../shared/generated/time-pilot-font.h linker.cfg
EXTRA_FLAGS := -C linker.cfg
RELEASE_FLAGS := -O

include ../../mk/program.mk
