PROGRAM := tilemap_scroll_demo
SOURCES := main.c ../../shared/tilebuffer/tilebuffer.c
EXTRA_DEPS := ../../shared/generated/time-pilot-font.h \
              ../../shared/generated/time-pilot-parachutists.h linker.cfg
EXTRA_FLAGS := -C linker.cfg
RELEASE_FLAGS := -O

include ../../mk/program.mk
