#!/usr/bin/env python3
"""Decode Time Pilot's tm4/tm5 sprite ROMs using MAME's spritelayout."""

import argparse
import hashlib
import struct
import zlib
from pathlib import Path


EXPECTED_TM4_SHA1 = "cbe2ccd2cd503af62f009cd5aab73aa7366230b1"
EXPECTED_TM5_SHA1 = "5dd30d3fb9fd8cf9e6a8e37e7ea858c7fd038a7e"
SPRITE_COUNT = 256
SPRITE_WIDTH = 16
SPRITE_HEIGHT = 16
SOURCE_BYTES_PER_SPRITE = 64
OUTPUT_BYTES_PER_SPRITE = 128  # MEGA65 4-bpp: two pixels per byte.

# Deliberately independent of the arcade PROMs. Pixel value zero is shown as
# a dark background; the other three values are easy to distinguish.
FALLBACK_COLOURS = (
    (8, 8, 24),
    (230, 230, 230),
    (194, 0, 194),
    (0, 77, 255),
)


def checked_rom(path, expected_sha1):
    data = Path(path).read_bytes()
    digest = hashlib.sha1(data).hexdigest()
    if len(data) != 8192:
        raise ValueError(f"{path} has {len(data)} bytes, expected 8192")
    if digest != expected_sha1:
        raise ValueError(f"unexpected {Path(path).name} SHA-1: {digest}")
    return data


def decode_sprite(rom, sprite_index):
    """Implement MAME's 16x16, 2-bpp Time Pilot spritelayout."""
    base = sprite_index * SOURCE_BYTES_PER_SPRITE
    pixels = []
    for y in range(SPRITE_HEIGHT):
        row_offset = (y & 7) + (32 if y >= 8 else 0)
        for group in range(4):
            value = rom[base + row_offset + group * 8]
            for x in range(4):
                # MAME plane offsets are {4,0}. As with tm6, the low nibble
                # contributes pixel bit 0 and the high nibble pixel bit 1.
                plane0 = (value >> (3 - x)) & 1
                plane1 = (value >> (7 - x)) & 1
                pixels.append(plane0 | (plane1 << 1))
    return pixels


def rotate_upright(pixels):
    """Rotate portrait-monitor ROM art 90 degrees clockwise."""
    return [pixels[(SPRITE_HEIGHT - 1 - x) * SPRITE_WIDTH + y]
            for y in range(SPRITE_HEIGHT) for x in range(SPRITE_WIDTH)]


def pack_mega65_4bpp(pixels):
    return bytes((pixels[i] << 4) | pixels[i + 1]
                 for i in range(0, len(pixels), 2))


def png_chunk(kind, payload):
    return (struct.pack(">I", len(payload)) + kind + payload +
            struct.pack(">I", zlib.crc32(kind + payload) & 0xFFFFFFFF))


def write_sheet(path, sprites, columns=16):
    rows = (len(sprites) + columns - 1) // columns
    width = columns * SPRITE_WIDTH
    height = rows * SPRITE_HEIGHT
    image = [bytearray(width * 3) for _ in range(height)]

    for index, sprite in enumerate(sprites):
        origin_x = (index % columns) * SPRITE_WIDTH
        origin_y = (index // columns) * SPRITE_HEIGHT
        for y in range(SPRITE_HEIGHT):
            for x in range(SPRITE_WIDTH):
                colour = FALLBACK_COLOURS[sprite[y * SPRITE_WIDTH + x]]
                offset = (origin_x + x) * 3
                image[origin_y + y][offset:offset + 3] = bytes(colour)

    raw = b"".join(b"\x00" + bytes(row) for row in image)
    png = (b"\x89PNG\r\n\x1a\n" +
           png_chunk(b"IHDR", struct.pack(">IIBBBBB", width, height,
                                           8, 2, 0, 0, 0)) +
           png_chunk(b"IDAT", zlib.compress(raw, 9)) +
           png_chunk(b"IEND", b""))
    Path(path).write_bytes(png)


def write_header(path):
    Path(path).write_text("""/* Generated by tools/extract_timepilot_sprites.py; do not edit. */
#ifndef TIME_PILOT_SPRITES_H
#define TIME_PILOT_SPRITES_H

#define TIME_PILOT_SPRITE_COUNT 256
#define TIME_PILOT_SPRITE_WIDTH 16
#define TIME_PILOT_SPRITE_HEIGHT 16
#define TIME_PILOT_SPRITE_BYTES 128
#define TIME_PILOT_SPRITE_DATA_SIZE 32768

/* The corresponding .bin contains sprite codes 0..255 consecutively. */
#define TIME_PILOT_SPRITE_OFFSET(code) ((unsigned int)(code) * 128U)

#endif
""")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("rom_dir")
    parser.add_argument("output_bin")
    parser.add_argument("output_png")
    parser.add_argument("output_header")
    args = parser.parse_args()

    rom_dir = Path(args.rom_dir)
    tm4 = checked_rom(rom_dir / "tm4", EXPECTED_TM4_SHA1)
    tm5 = checked_rom(rom_dir / "tm5", EXPECTED_TM5_SHA1)
    rom = tm4 + tm5
    sprites = [rotate_upright(decode_sprite(rom, index))
               for index in range(SPRITE_COUNT)]

    output_bin = Path(args.output_bin)
    output_bin.parent.mkdir(parents=True, exist_ok=True)
    output_bin.write_bytes(b"".join(pack_mega65_4bpp(sprite)
                                    for sprite in sprites))
    write_sheet(args.output_png, sprites)
    write_header(args.output_header)


if __name__ == "__main__":
    main()
