#!/usr/bin/env python3
"""Extract reusable 16x16 cloud sprites from the normalized Time Pilot map."""

import argparse
from pathlib import Path

import png_tile


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("input")
    parser.add_argument("output")
    args = parser.parse_args()

    width, height, rows = png_tile.read_rgba_png(args.input)
    if (width, height) != (256, 256):
        raise ValueError("expected the normalized 256x256 tilemap")

    rgba_frames = []
    for tile_x in range(12, 16):
        frame = []
        for y in range(5 * 16, 6 * 16):
            for x in range(tile_x * 16, (tile_x + 1) * 16):
                frame.append(tuple(rows[y][x * 4:x * 4 + 4]))
        rgba_frames.append(frame)

    colors = []
    for frame in rgba_frames:
        for color in frame:
            if color[3] >= 128 and color[:3] not in colors:
                colors.append(color[:3])
    if len(colors) > 15:
        raise ValueError(f"clouds use {len(colors)} opaque colors")
    palette = [(0, 0, 0)] + colors

    frames = []
    for frame in rgba_frames:
        indices = [0 if color[3] < 128 else palette.index(color[:3]) for color in frame]
        frames.append([(indices[i] << 4) | indices[i + 1] for i in range(0, 256, 2)])

    lines = [
        "/* Generated by tools/time_pilot_clouds.py; do not edit. */",
        "#ifndef TIME_PILOT_CLOUDS_H",
        "#define TIME_PILOT_CLOUDS_H",
        "",
        f"#define CLOUD_PALETTE_SIZE {len(palette)}",
        "#define CLOUD_FRAME_COUNT 4",
        "#define CLOUD_FRAME_SIZE 128",
        "",
        "static const unsigned char cloud_palette[CLOUD_PALETTE_SIZE][3] = {",
    ]
    lines += [f"    {{{r}, {g}, {b}}}," for r, g, b in palette]
    lines += ["};", "", "static const unsigned char cloud_frames[4][128] = {"]
    for frame in frames:
        lines.append("    {")
        for offset in range(0, 128, 8):
            values = ", ".join(f"0x{value:02X}" for value in frame[offset:offset + 8])
            lines.append(f"        {values},")
        lines.append("    },")
    lines += ["};", "", "#endif", ""]
    Path(args.output).write_text("\n".join(lines))


if __name__ == "__main__":
    main()
