#!/usr/bin/env python3
"""Extract Time Pilot's original first-era clouds from tm4/tm5."""

import argparse
from pathlib import Path

import extract_timepilot_sprites as sprites


# Z80 table $3176 contains eight hardware-sprite codes per era. The MEGA65
# demo reserves slot 0 for the player. The original groups its eight slots as
# 3+2+2+1; retain the complete first three compound clouds and omit only the
# final standalone $5c cloud.
FIRST_ERA_CLOUD_CODES = (0x60, 0x68, 0x61, 0x60, 0x61, 0x62, 0x63)

# Temporary direct pixel-value palette until the original sprite PROM lookup
# is implemented. Pixel zero remains transparent in MEGA65 16-colour sprites.
CLOUD_PALETTE = (
    (0, 0, 0),
    (191, 191, 191),
    (130, 130, 130),
    (166, 166, 166),
)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("rom_dir")
    parser.add_argument("output")
    args = parser.parse_args()

    rom_dir = Path(args.rom_dir)
    tm4 = sprites.checked_rom(rom_dir / "tm4", sprites.EXPECTED_TM4_SHA1)
    tm5 = sprites.checked_rom(rom_dir / "tm5", sprites.EXPECTED_TM5_SHA1)
    rom = tm4 + tm5
    frames = [sprites.pack_mega65_4bpp(sprites.rotate_upright(
                  sprites.decode_sprite(rom, code)))
              for code in FIRST_ERA_CLOUD_CODES]

    lines = [
        "/* Generated by tools/time_pilot_clouds.py; do not edit. */",
        "#ifndef TIME_PILOT_CLOUDS_H",
        "#define TIME_PILOT_CLOUDS_H",
        "",
        f"#define CLOUD_PALETTE_SIZE {len(CLOUD_PALETTE)}",
        f"#define CLOUD_FRAME_COUNT {len(frames)}",
        "#define CLOUD_FRAME_SIZE 128",
        "",
        "static const unsigned char cloud_palette[CLOUD_PALETTE_SIZE][3] = {",
    ]
    lines += [f"    {{{r}, {g}, {b}}}," for r, g, b in CLOUD_PALETTE]
    code_list = ", ".join(f"${code:02x}" for code in FIRST_ERA_CLOUD_CODES)
    lines += ["};", "", "#ifdef TIME_PILOT_CLOUD_DATA_SEGMENT",
              "#pragma rodata-name (\"CLOUDDATA\")", "#endif", "",
              f"/* Original Z80 $3176 codes: {code_list}. */",
              f"static const unsigned char cloud_frames[{len(frames)}][128] = {{"]
    for frame in frames:
        lines.append("    {")
        for offset in range(0, 128, 8):
            values = ", ".join(f"0x{value:02X}" for value in frame[offset:offset + 8])
            lines.append(f"        {values},")
        lines.append("    },")
    lines += ["};", "", "#ifdef TIME_PILOT_CLOUD_DATA_SEGMENT",
              "#pragma rodata-name (\"RODATA\")", "#endif", "", "#endif", ""]
    Path(args.output).write_text("\n".join(lines))


if __name__ == "__main__":
    main()
