#!/usr/bin/env python3
"""Extract the four original Time Pilot parachutist animation frames."""

import argparse
from pathlib import Path

import extract_timepilot_sprites as sprites


PARACHUTIST_CODES = (0x00, 0x01, 0x02, 0x03)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("rom_dir")
    parser.add_argument("output")
    args = parser.parse_args()

    rom_dir = Path(args.rom_dir)
    rom = (sprites.checked_rom(rom_dir / "tm4", sprites.EXPECTED_TM4_SHA1) +
           sprites.checked_rom(rom_dir / "tm5", sprites.EXPECTED_TM5_SHA1))
    frames = [sprites.pack_mega65_4bpp(sprites.rotate_upright(
                  sprites.decode_sprite(rom, code)))
              for code in PARACHUTIST_CODES]

    lines = [
        "/* Generated by tools/time_pilot_parachutists.py; do not edit. */",
        "#ifndef TIME_PILOT_PARACHUTISTS_H",
        "#define TIME_PILOT_PARACHUTISTS_H",
        "",
        f"#define PARACHUTIST_FRAME_COUNT {len(frames)}",
        "#define PARACHUTIST_FRAME_SIZE 128",
        "",
        "/* Original sprite codes $00-$03. */",
        f"static const unsigned char parachutist_frames[{len(frames)}][128] = {{",
    ]
    for frame in frames:
        lines.append("    {")
        for offset in range(0, 128, 8):
            values = ", ".join(f"0x{value:02X}" for value in frame[offset:offset + 8])
            lines.append(f"        {values},")
        lines.append("    },")
    lines += ["};", "", "#endif", ""]
    Path(args.output).write_text("\n".join(lines))


if __name__ == "__main__":
    main()
