#!/usr/bin/env python3
"""Build the 17 source frames needed for a 32-direction Time Pilot plane."""

import argparse
from pathlib import Path

import png_tile


def flip_vertical(packed):
    rows = [packed[offset:offset + 8] for offset in range(0, 128, 8)]
    return [value for row in reversed(rows) for value in row]


def extract_pixels(rows, start_x, start_y):
    return [
        tuple(rows[start_y + y][(start_x + x) * 4:(start_x + x) * 4 + 4])
        for y in range(16)
        for x in range(16)
    ]


def pack_pixels(pixels, palette):
    indices = [0 if color[3] < 128 else palette.index(color[:3]) for color in pixels]
    return [(indices[i] << 4) | indices[i + 1] for i in range(0, 256, 2)]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("input")
    parser.add_argument("output")
    parser.add_argument("--segment", help="cc65 RODATA segment for generated tables")
    args = parser.parse_args()

    _, _, rows = png_tile.read_rgba_png(args.input)
    positions = (
        [(128 + index * 16, 224) for index in range(8)] +
        [(index * 16, 240) for index in range(8)]
    )
    rgba_frames = [extract_pixels(rows, x, y) for x, y in positions]
    opaque_colors = []
    for frame in rgba_frames:
        for color in frame:
            if color[3] >= 128 and color[:3] not in opaque_colors:
                opaque_colors.append(color[:3])
    if len(opaque_colors) > 15:
        raise ValueError(f"plane frames use {len(opaque_colors)} opaque colors")
    palette = [(0, 0, 0)] + opaque_colors
    frames = [pack_pixels(frame, palette) for frame in rgba_frames]

    # The sheet stops one step before south; south is north mirrored vertically.
    frames.append(flip_vertical(frames[0]))

    lines = [
        "/* Generated by tools/time_pilot_flight.py; do not edit. */",
        "#ifndef TIME_PILOT_FLIGHT_H",
        "#define TIME_PILOT_FLIGHT_H",
        "",
        f"#define FLIGHT_PALETTE_SIZE {len(palette)}",
        "#define FLIGHT_SOURCE_FRAME_COUNT 17",
        "#define FLIGHT_FRAME_SIZE 128",
        "",
    ]
    if args.segment:
        lines += [f'#pragma rodata-name ("{args.segment}")', ""]
    lines += ["static const unsigned char flight_palette[FLIGHT_PALETTE_SIZE][3] = {"]
    lines += [f"    {{{red}, {green}, {blue}}}," for red, green, blue in palette]
    lines += ["};", "", "static const unsigned char flight_frames[17][128] = {"]
    for frame in frames:
        lines.append("    {")
        for offset in range(0, 128, 8):
            values = ", ".join(f"0x{value:02X}" for value in frame[offset:offset + 8])
            lines.append(f"        {values},")
        lines.append("    },")
    lines += ["};", ""]
    if args.segment:
        lines += ['#pragma rodata-name ("RODATA")', ""]
    lines += ["#endif", ""]

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
