PROGRAM := sprite_multiplexer_demo
SOURCES := main.c \
    ../../shared/sprite_multiplexer/sprite_multiplexer.c \
    ../../shared/sprite_multiplexer/sprite_multiplexer_irq.s
EXTRA_DEPS := ../../shared/generated/time-pilot-clouds.h \
    ../../shared/sprite_multiplexer/sprite_multiplexer.h

include ../../mk/program.mk
